### ISSUE TITLE
implement search function

### ISSUE THREAD

**Issue by amay5267** [Tomas-M/mini-commander#2]
Hi @Tomas-M 

Can you implement search option?

**Comment by amay5267** [comment]
Shift ALT ?

**Comment by Tomas-M** [comment]
You mean Alt+s ?

**Comment by amay5267** [comment]
mc implemented  SHIFT + ALT + ?

**Comment by Tomas-M** [comment]
I do not know anything like this and it does nothing in my mc.
I only know Alt+s shortcut, which starts search mode in current panel.

**Comment by amay5267** [comment]
how to list all files in current dir and subdirs (flat-view) in mc?

**Comment by Tomas-M** [comment]
This does not exist in mini commander and there is no plan to implement it

**Comment by amay5267** [comment]
ok

**Comment by Tomas-M** [comment]
Alt+s for search is currently planned
