### ISSUE TITLE
background colors of texts

### ISSUE THREAD

**Issue by vaguinerg** [Tomas-M/mini-commander#4]
hello, the program dont gives a good colorization when with --no-colors.
https://i.imgur.com/pmiNsn5.png
The background is supposed to be transparent? (no color) but a color is applied to the background of each text.

**Comment by vaguinerg** [comment]
something like this is expected
http://bp3.blogger.com/_HXuKv2YS8fM/SCSBfKdpZ5I/AAAAAAAAAFA/UrRXW-LYF5k/s1600-h/mc-transparent.png

**Comment by Tomas-M** [comment]
Yellow is a color. Nocolor is basically black and white

**Comment by vaguinerg** [comment]
@Tomas-M the image I showed was just a reference, the point is that you are applying a color to the background of the text, and you should only apply color to the text with nocolor
