### ISSUE TITLE
opens with "/root" as right_panel.path

### ISSUE THREAD

**Issue by LinuxWelt** [Tomas-M/mini-commander#5]
I would not recommend having mini-commander open the path "/root" in the right panel because user has no permissions to view this folder. 
In order to change that, in mc.c replace the line (118)

`strcpy(right_panel.path,"/root"); `

with

`strcpy(right_panel.path,right_panel.path); `

and both panels will open the home directory by default.

**Comment by Tomas-M** [comment]
updated. please try to compile and let me know if this works for you

**Comment by LinuxWelt** [comment]
Hi Tomas,
thanks, much better now.

The previous version of mini-commander would core dump after started as an unprivileged user when changing to /root in the right  panel.

You may mark this issue as closed.
